name: dcrypto
description: A starting point for Dart libraries or applications.
version: 0.3.0
repository: https://github.com/PumpkinSeed/dcrypto

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  encrypt: ^5.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
